apiVersion: v1
kind: ConfigMap
metadata:
  name: financials-tracker-2-config
  namespace: financials-tracker-2
  labels:
    app: financials-tracker-2
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  SPRING_PROFILES_ACTIVE: prod
  PORT: "8080"
  DB_HOST: postgres.postgres.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: financials-tracker-2
  JPA_DDL_AUTO: update
  JPA_SHOW_SQL: "false"
  JWT_EXPIRATION_MS: "86400000"
